### ISSUE TITLE
Bulk creation of channels

### ISSUE THREAD

**Issue by simongregorebner** [channelaccess/ca#12]
Besides the current base methods to create channels I guess there should be some convenience method to bulk create channels. This method should accept a list/set/map of channels and create and connect all of these.

We could somehow adopt the way jcae does it right now, i.e. via ChannelDescriptor (this current solution however needs to be revised somehow though).
If we go that route (channel descriptor), eventually we change the base methods as well to accept a channel descriptor ... - however then we have to distinguish the methods that automatically connect the channels and which do not ...

**Comment by simongregorebner** [comment]
(Matej) I would move “Bulk creation of channels” into util class

**Comment by simongregorebner** [comment]
Here I would propose then something like this ...

```java
Context context = ...
List<ChannelDescriptor> descriptors = ...

List<Channel> channels = Channels.create( context, descriptors)
```

**Comment by msekoranja** [comment]
Looks OK.
What is definition of `ChannelDescriptor`?

**Comment by simongregorebner** [comment]
Actually we could have different kind of descriptors
The base one with:

```java
// ... 
        public ChannelDescriptor(Class<T> type, String name){
		//...
	}
	
	public ChannelDescriptor(Class<T> type, String name, boolean monitored){
		//...
	}
	
	public ChannelDescriptor(Class<T> type, String name, boolean monitored, Integer size){
            //...
	}
// ...
```
or even less

then some descriptor which could eventually build a channel based on set/readback channel ...
