### ISSUE TITLE
Convenience Functions - waitFor()

### ISSUE THREAD

**Issue by simongregorebner** [channelaccess/ca#15]
while working with the ca library I got the feeling it might be good to add some more convenience functions the Channel interface.
The methods I think of are:

waitFor(T value);
waitFor(T value, Comparator comparator);

CompletableFuture f = waitForAsync(T value);
CompletableFuture f = waitForAsync(T value, Comparator comparator);

Regarding the names of the function I am not sure whether to just use waitFor or waitForValue .

“Within" these functions what I would do is, attaching a monitor, waiting on the value and then detaching the monitor ...

What do you think of this?
Would this make sense?

**Comment by simongregorebner** [comment]
These functions make sense, however this function should not be part of Channel, since CA does not provide any special support for it.
Also I do not want to pollute API. Functions should go to some util class.

Matej

**Comment by simongregorebner** [comment]
So here we go with this?

```java
Channels.waitForValue(channel, value);
Channels.waitForValue(channel, value, comparator);

Channels.waitForValueAsync(channel, value);
Channels.waitForValueAsync(channel, value, comparator);
```

**Comment by msekoranja** [comment]
Yep.
