### ISSUE TITLE
Specifying Unicast Address in ADDR_LIST does not work

### ISSUE THREAD

**Issue by simongregorebner** [channelaccess/ca#6]
When specifying a unicast address in the address list properties the channel will not be found.(It works if specifying the broadcast address)

This is the test code I used (the channel ARIDI-PCT:CURRENT is on the machine 129.129.130.20 ):

```Java
public static void main(String[] args) throws InterruptedException, ExecutionException, TimeoutException {
		Properties properties = new Properties();
		properties.setProperty(Constants.ADDR_LIST_KEY, "129.129.130.20");
//		properties.setProperty(Constants.ADDR_LIST_KEY, "129.129.130.255"); // this works
		try (Context context = new Context(properties))
		{
		  Channel<Double> channel = context.createChannel("ARIDI-PCT:CURRENT", Double.class);
		  channel.connectAsync().get(1, TimeUnit.SECONDS);
		  System.out.println(channel.getProperties());
		  System.out.println(channel.get());
		  channel.close();
		}
	}
```

**Comment by msekoranja** [comment]
Try the following:

export EPICS_CA_ADDR_LIST=129.129.130.20
cainfo ARIDI-PCT:CURRENT

using the same configuration (computer, system env. variables, etc).

**Comment by simongregorebner** [comment]
export EPICS_CA_ADDR_LIST=129.129.130.20
ebner@gfa-lc6-64:~$ cainfo ARIDI-PCT:CURRENT
can't find channel ARIDI-PCT:CURRENT
ebner@gfa-lc6-64:~$ 

doesn’t work either, so its not a library problem…
