### ISSUE TITLE
Improvement nativeType property of a channel

### ISSUE THREAD

**Issue by simongregorebner** [channelaccess/ca#8]
While getting the property nativeType from a channel the return value is a number 
It would be great if it would return the actual Java type:

channel.getProperties().get("nativeType")
>> 6

ideally this would be 
channel.getProperties().get("nativeType")
>> Double.class

or something like this ...

or is there a way to map the number to the type?

**Comment by msekoranja** [comment]
Renamed current "nativeType" to "nativeTypeCode".
Added "nativeType" to return a class as described above.
